spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        -Account: AccountService
          Uri: lb://AccountService
          predicates:
            -Path=/account
        -Analysis: AnalysisService
          Uri: lb://AnalysisService
          predicates:
            -Path=/analysis
        -Card: CreditCardService
          Uri: lb://CreditCardService
          predicates:
            -Path=/cards
        -Loans:
          Uri: lb://LoanService
          predicates:
            -Path=/loans
        -Client:
          Uri: lb://ClientService
          predicates:
            -Path=/**

