spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: AccountService
          uri: lb://AccountService
          predicates:
            - Path=/account/**
        - id: AnalysisService
          uri: lb://AnalysisService
          predicates:
            - Path=/analysis/**
        - id: CreditCardService
          uri: lb://CreditCardService
          predicates:
            - Path=/cards/**
        - id: LoanService
          uri: lb://LoanService
          predicates:
            - Path=/loans/**
#        - id:
#          uri: lb://ClientService
#          predicates:
#            - Path=/**

